[package]
name = "qn"
version = "0.1.0"
edition = "2021"
description = "Qubit type"
homepage = "https://github.com/marek-miller/qn"
license = "MIT"
readme = "README.md"
repository = "https://github.com/marek-miller/qn.git"


[dependencies]
